dbgprint: False # отладка
mincluster: 0 # учитываем только кластера с размером >= этого значения
lambda_heal: 1. # скорость выздоровления
maxtags: -1  # максимальное число заражений от одного узла
infect_lamda: .1
MAXITER: 5000 # 0 # число каскадов для каждого infect_lamda
minsize: 2 # минимальный размер каскада